services: 
  backend: 
    build: ./backend
    volumes:
      - backend_vol:/app
    ports: 
      - 8000:8000
  frontend: 
    build: ./frontend
    volumes: 
      - frontend_vol:/app
    ports: 
      - 3000:3000
    depends_on: 
      - backend
volumes:
  backend_vol:
  frontend_vol: